# Generated by Django 5.0.6 on 2024-06-12 19:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0002_blacklistedaccesstoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_staff_member",
            field=models.BooleanField(default=False),
        ),
    ]
