# Generated by Django 5.0.6 on 2024-06-16 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_customuser_is_admin_customuser_is_staff_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentslist',
            name='application_status',
            field=models.CharField(choices=[('Interested', 'Interested'), ('Not Interested', 'Not Interested'), ('Callback', 'Callback'), ('No Response', 'No Response')], default='Interested', max_length=15),
        ),
        migrations.AddField(
            model_name='studentslist',
            name='city',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='studentslist',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentslist',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Not Selected', max_length=6),
        ),
        migrations.AddField(
            model_name='studentslist',
            name='graduation_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentslist',
            name='intended_degree',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='studentslist',
            name='intended_field_of_study',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='studentslist',
            name='pin_code',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='studentslist',
            name='preferred_location',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='studentslist',
            name='state',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
